[package]
name = "playaround"
version = "0.1.0"
edition = "2024"

[dependencies]
ethers = "2.0.14"
reqwest = { version = "0.12.23", features = ["json"] }
serde_json = "1.0.143"
tokio = { version = "1.47.1", features = ["full"] }
my_proc_macro = {path = "./my_proc_macro"}